# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present

      - name: Deploy to Nginx
        run: |
          # Stop Nginx
          sudo systemctl stop nginx

          # Copy Nginx config
          sudo cp nginx.conf /etc/nginx/sites-available/levelup.conf
          sudo ln -sf /etc/nginx/sites-available/levelup.conf /etc/nginx/sites-enabled/

          # Clear and prepare directory
          sudo rm -rf /var/www/levelup/*
          sudo mkdir -p /var/www/levelup
          sudo chown -R $USER:$USER /var/www/levelup

          # Copy new build files
          sudo cp -r dist/* /var/www/levelup/

          # Set permissions
          sudo chown -R www-data:www-data /var/www/levelup
          sudo chmod -R 755 /var/www/levelup

          # Start Nginx
          sudo nginx -t && sudo systemctl start nginx && sudo systemctl reload nginx
